# Generated by Django 5.0 on 2024-03-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortFolio', '0003_remove_profilevisitlink_qr_code_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilevisitlink',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
